name: heroicons
description: Easily use the heroicons set in your Flutter app.
version: 0.8.1
homepage: https://github.com/vaetas/heroicons

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  path: ^1.8.3

dev_dependencies:
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  recase: ^4.1.0

flutter:
  assets:
    - assets/
    - assets/outline/
    - assets/solid/
    - assets/mini/
