name: heroicons
description: HeroIcons set of SVG icons in your Flutter app. Both outlined & solid icon version are available.
version: 0.7.0
homepage: https://github.com/vaetas/heroicons

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  path: ^1.8.2

dev_dependencies:
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  recase: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/outline/
    - assets/solid/
    - assets/mini/
